### ISSUE TITLE
[feature] Keybinding to save image to directory

### ISSUE THREAD

**Issue by oestrommunism** [artemsen/swayimg#67] opened 2023-02-22 17:03 UTC
Hi! i use swayimg (and i love it) to view images inside a mastodon tui and sometimes i want to be able to save the image that is being displayed, but i have to take a screenshot or copy it manually from tmp. Is it possible to add a keybind to save the image to a directory?

**Comment by artemsen** [comment] 2023-02-23 06:08
Swayimg cannot save the original image to a file, because after decoding, the image is stored in memory as a raw array of RGBA pixels. We need to re-encode this data back, but this will result in loss of quality and metadata.
How do you load original images? From a file or a pipe?

**Comment by artemsen** [comment] 2023-02-23 08:33
I added support for external command (default key `e`).
You can set the command to be executed via the Swayimg arguments:
```
swayimg -e 'cp "%" /path/to/copy'
```

Is this functionality enough for you?

**Comment by oestrommunism** [comment] 2023-02-23 13:38
Wow! thanks for the quick reply :D this works perfectly when i run it by itself but when i put it into the toml for tut it has a problem with using % to define the file i want copied. 

when i press the display key in tut it seems like it downloads the file to /tmp and it renames it to "tutfile" with 9 random digits (ie: tutfile236072347.png) and then that is passed to swayimg to display. swayimg displays the file fine like this,  but when i press the e key swayimg returns : 
'%': [2] No such file or directory
cp: missing file operand

i'm not sure if this is more of an issue with tut at this point because if i am understanding the e flag you added it should be possible for me to write a small script that looks for the most recent image in /tmp and moves it? Thanks so much for your time

**Comment by artemsen** [comment] 2023-02-23 14:54
> '%': [2] No such file or directory

Looks like a bug, but I can't reproduce it.
Could you set `-e echo %` and grab stdout?

**Comment by oestrommunism** [comment] 2023-02-23 16:38
i think so; using 
`swayimg -e echo %  test.png 2>&1 | tee outfile`
displays the image and the contents of outfile are just 
`%: [2] No such file or directory`

since i am using this in tut i also added "-e echo %" to it's config and it returns the same thing. 

i think the source of the issue has to do with how the toml file parses the syntax in " swayimg -e 'cp "%" /path/to/copy' ". I wrote a small script to find the last file named "tutfile" in /tmp and then i told tut to use what i wrote as the image display program. The -e flag works wonderfully and was just what i needed to make it work. <3

here's what i wrote as a workaround for tut for anyone else who happens across this same issue. it's probably ugly but it worked for me 😊

`#!bin/bash`
`last=/tmp/$(ls /tmp -Art | grep tutfile | tail -n1`
`swayimg -e "cp $last ~/Pictures/tut" $last`

**Comment by artemsen** [comment] 2023-02-24 06:33
> `swayimg -e echo %  test.png 2>&1 | tee outfile`

I guess you forgot about the quotes, so Swayimg tries to execute "echo" and open the "%" and "test.png" files.

> The -e flag works wonderfully and was just what i needed to make it work. <3

Thank you! I close this issue.

**Closed by artemsen** 2023-02-24 06:33 UTC
