### ISSUE TITLE
Config keybinds doesn't override old ones

### ISSUE THREAD

**Issue by hecto600** [artemsen/swayimg#203] opened 2024-10-19 02:09 UTC
I created new bindings in [keys.viewer] section of the config file. It works but it doesn't override the old ones. The help menu shows the old config and appended the new ones at the end of the list.
![swappy-2024-10-18_230546](https://github.com/user-attachments/assets/052d435c-5c15-470e-ad18-089ace1f2d32)

**Comment by artemsen** [comment] 2024-10-19 10:05
Duplicate of #202

**Closed by artemsen** 2024-10-19 10:05 UTC
Labels: bug, duplicate
